---
# tasks file for tomcat8
- name: install the latest version of java
  yum:
    name: java-1.7.0-openjdk-devel
    state: latest


- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: Create a tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: Add the user tomcat 
  user:
    name: tomcat
    shell: /bin/nologin
    groups: tomcat


- name: grant tomcat directory permision
  file:
    path: /opt/tomcat
    mode: '0755'
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Download tomcat
  get_url:
    url: "{{ tomcat_link }}"
    dest: /opt

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /opt/{{ tomcat_pkg }}
    dest: /opt/tomcat
    remote_src: yes


- name: grant tomcat directory permision
  file:
    path: /opt/tomcat
    mode: '0775'
    owner: tomcat
    group: tomcat
    recurse: yes

- name: copy tomcat service
  copy:
    src: files/tomcat.service
    dest: /etc/systemd/system
